### ISSUE TITLE
 Cannot read property 'message' of undefined

### ISSUE THREAD

**Issue by huanjulu** [MarnoDev/HelloRN#9]
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

(node:82393) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at handleError (/Users/huanjulu/Documents/workpace/RNdemo/HelloRN/node_modules/react-native/local-cli/cliEntry.js:35:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(node:82393) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:82393) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by done134** [comment]
您好，请问你这个问题解决了没有

**Comment by hemantparakh** [comment]
I am new to react-native. Trying to run sample app first time. I am also facing similar issue when run-desktop app.
react-native-desktop\react-native-cli\DesktopSampleApp> react-native run-desktop

C:\Projects\React-native\react-native\react-native-desktop\react-native-cli\DesktopSampleApp\desktop>cmake -DCMAKE_BUILD_TYPE=Debug -G "MinGW Makefiles" -DEXTERNAL_MODULES_DIR= -DJS_BUNDLE_PATH= -DDESKTOP_FONTS= -DDESKTOP_IMAGES= .   && cmake --build .

stderr: 'cmake' is not recognized as an internal or external command,
operable program or batch file.

child process exited with code 1

(node:44492) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined
    at handleError (C:\Projects\React-native\react-native\react-native-desktop\react-native-cli\DesktopSampleApp\node_modules\react-native\local-cli\cliEntry.js:39:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:44492) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:44492) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
      Memory: 6.57 GB / 15.89 GB
    Binaries:
      npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD

I feel some environment issue. Can anyone help to resolve this issue?
